name: Node.js CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 18
      - run: npm ci
      - run: npm run lint
      - run: npm test
        env:
          FORCE_COLOR: true
      - run: npm run build
      - run: npm pack
      - run: mv rxjest-*.tgz package.tgz
      - uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error
          name: package
          path: package.tgz
  verify:
    runs-on: ubuntu-22.04
    needs: test
    strategy:
      matrix:
        include:
          - jest: 27
            node: 18
            rxjs: 7
          - jest: 28
            node: 18
            rxjs: 7
          - jest: 29
            node: 18
            rxjs: 7
          - jest: 29
            node: 14
            rxjs: 7
          - jest: 29
            node: 16
            rxjs: 7
          - jest: 29
            node: 18
            rxjs: 6
          - jest: 29
            node: 20
            rxjs: 7
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - if: matrix.node == 14
        run: npm install --global npm@8
      - uses: actions/download-artifact@v3
        with:
          name: package
      - run: npm run e2e -- local
        env:
          JEST_VERSION: ${{ matrix.jest }}
          RXJS_VERSION: ${{ matrix.rxjs }}
  deploy:
    runs-on: ubuntu-22.04
    if: startsWith(github.ref, 'refs/tags/v')
    needs: verify
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/download-artifact@v3
        with:
          name: package
      - run: npm config set '//registry.npmjs.org/:_authToken' "${NPM_AUTH_TOKEN}"
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - run: npm publish package.tgz
  smoke:
    runs-on: ubuntu-22.04
    needs: deploy
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm run e2e -- "${TAG_REF#refs/tags/v}"
        env:
          TAG_REF: ${{ github.ref }}
